### ISSUE TITLE
MG autoscroll issue

### ISSUE THREAD

**Issue by ghost** [lemon-juice/mouse-gestures-suite#1]
I have problem with press-move-release mode of autoscroll.
Most of the time, cursor stays in autoscroll mode, instead of returning to normal navigation after release. Must be some timer issue, because when I do this slowly (on long page), all is OK.

Testing:
open page, press middle button, move mouse to scroll to the bottom, release button

working here (long page)
 https://addons.mozilla.org/en-US/firefox/addon/mouse-gestures-suite/
but not working here (short page)
 http://lemon-juice.github.io/mouse-gestures-suite/

**Comment by lemon-juice** [comment]
On 2015-06-03 21:35, gwarser wrote:

> I have problem with press-move-release mode of autoscroll.
> Most of the time, cursor stays in autoscroll mode, instead of 
> returning to normal navigation after release. Must be some timer 
> issue, because when I do this slowly (on long page), all is OK.
> 
> Testing:
> open page, press middle button, move mouse to scroll to the bottom, 
> release button
> 
> working here (long page)
> https://addons.mozilla.org/en-US/firefox/addon/mouse-gestures-suite/
> but not working here (short page)
> http://lemon-juice.github.io/mouse-gestures-suite 
> http://lemon-juice.github.io/mouse-gestures-suite/
> 
> Hi,

I can't reproduce this problem. Could you send me your settings exported 
from the mouse gestures options? Also, what OS are you using and what 
browser?

**Comment by ghost** [comment]
http://pastebin.com/hQGk8MVc
Firefox 39b2 on win7, 64bit

**Comment by lemon-juice** [comment]
Yes, it turned out to be a timeout of 1 second applied to auto scroll with the button depressed.

Try the fixed version 2.1.3 [here](https://addons.mozilla.org/addon/mouse-gestures-suite/versions/) and let me know if this works for you.

**Comment by ghost** [comment]
Looks good. Thank you.
