### ISSUE TITLE
Feature Request: Configurable timeout for gesture abortion

### ISSUE THREAD

**Issue by schnz** [lemon-juice/mouse-gestures-suite#13]
Several months ago I swtiched from [https://addons.mozilla.org/de/firefox/addon/all-in-one-gestures](All-in-One Gestures) to your addon because of compatibility issues with the old addon.
I am very happy with your addon but I fail to get used to one particular thing: The geasture timeout of 2s (I believe it is 2s).

In the old addon the timeout was significantly lower (I believe ~1s or even less). Could you add an option for configuring this timeout manually (preferably in ms)?

**Comment by lemon-juice** [comment]
Added option to change timeout in 2.5.0.

BTW, in All-In-One Gestures the timeout was 500ms and I changed it to 1000ms.

**Comment by schnz** [comment]
Thanks a lot :+1:
