### ISSUE TITLE
"Scroll wheel in tab bar" feature no longer works in Firefox 48

### ISSUE THREAD

**Issue by DJWalker** [lemon-juice/mouse-gestures-suite#14]
Upon updating to Firefox 48, I can no longer switch tabs using the scroll wheel even with this feature enabled.

**Comment by lemon-juice** [comment]
Thanks, I already know about it and fixed it. But I've noticed also a few other bugs in newest Firefox versions that I want to fix so I'll put up a new release with them all, soon.

**Comment by lemon-juice** [comment]
Fixed in 2.5.0
