### ISSUE TITLE
Duplicate Tab no longer duplicate history

### ISSUE THREAD

**Issue by NiarK** [lemon-juice/mouse-gestures-suite#2]
Hi,

When I use the "Duplicate Tab" gesture, it doesn't duplicate its history like before (I don't know since which version this issue start).
If I use firefox build-in shortcut (middle click on actualize button), the tab's history is normally duplicate.

Is there a way to restore this functionality?

Thanks a lot in advance,

Arnaud

**Comment by lemon-juice** [comment]
The "Duplicate Tab" gesture never preserved history in this extension - it worked in All-in-One Gestures and then after I made some adaptations for SeaMonkey it stopped doing that. But it was a nice feature - I'll have a fix soon!

**Comment by lemon-juice** [comment]
Done in version 2.3.0.

**Comment by NiarK** [comment]
Perfect, thank you very much!
Do you know when the 2.3.0 version will be there?

**Comment by lemon-juice** [comment]
It's already there waiting to be reviewed but you can grab it now: https://addons.mozilla.org/addon/mouse-gestures-suite/versions/

**Comment by NiarK** [comment]
Ok nice, it works perfectly!
