### ISSUE TITLE
Add an option to disable the popup in the bottom left corner

### ISSUE THREAD

**Issue by CamilleScholtz** [lemon-juice/mouse-gestures-suite#3]

**Comment by superkuh** [comment]
Please do add this option. The pop-ups often get stuck and I have to explicitly right click to make them go away. It's a great extension but the popup/tooltips are maddening.

**Comment by superkuh** [comment]
Although I haven't been able to get it to work in Pale Moon yet, it sounds like you fixed this in the latest 2.4.0 release. Thanks!
