### ISSUE TITLE
Hide info message at bottom on gesture execution?

### ISSUE THREAD

**Issue by dan-t** [lemon-juice/mouse-gestures-suite#6]
Is there a way to hide the info text appearing in the bottom
left corner when a mouse gesture is executed?

Thanks!

**Comment by superkuh** [comment]
While I agree, this issue is a repeat of https://github.com/lemon-juice/mouse-gestures-suite/issues/3 . Also, I don't think lemon-juice actually reads the github stuff.

**Comment by dan-t** [comment]
Ah, right, thanks.

**Comment by lemon-juice** [comment]
Sorry guys, I read these issues but I'm currently very busy and am not able to devote much time to development. But I'll definitely implement this feature in the next release, whenever I have more time.

**Comment by superkuh** [comment]
Thanks! That's all I could hope for.

**Comment by superkuh** [comment]
Sounds like you fixed this in the latest 2.4.0 release. Thanks!
